services:
  gateway-service:
    build:
      context: ./services/gateway
    container_name: gateway-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
    ports:
      - '2719:80'
    deploy:
      mode: replicated
      replicas: 1

  match-socket-service:
    build:
      context: ./services/match
    container_name: match-socket-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
    ports:
      - '2720:80'
    deploy:
      mode: replicated
      replicas: 1

  game-service:
    build:
      context: ./services/game
    container_name: game-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
      MONGO_HOST: mongo
      RABBITMQ_HOST: rabbitmq
    ports:
      - '2721:80'
    deploy:
      mode: replicated
      replicas: 1

  user-service:
    build:
      context: ./services/user
    container_name: user-service
    restart: always
    environment:
      MYSQL_HOST: mysql
      RABBITMQ_HOST: rabbitmq
    deploy:
      mode: replicated
      replicas: 1

  chat-service:
    build:
      context: ./services/chat
    container_name: chat-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
      MONGO_HOST: mongo
      RABBITMQ_HOST: rabbitmq
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./services/auth
    container_name: auth-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
      RABBITMQ_HOST: rabbitmq
    deploy:
      mode: replicated
      replicas: 1

  push-service:
    build:
      context: ./services/push
    container_name: push-service
    restart: always
    environment:
      ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID}
      ONESIGNAL_API_KEY: ${ONESIGNAL_API_KEY}
      MYSQL_HOST: mysql
      RABBITMQ_HOST: rabbitmq
    deploy:
      mode: replicated
      replicas: 1

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: sample
    ports:
      - '3306:3306'
    deploy:
      mode: replicated
      replicas: 1
    # volumes:
    #   - ./db-data/mysql/:/var/lib/mysql/

  mongo:
    image: 'mongo:4.2.16-bionic'
    container_name: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sample

  rabbitmq:
    image: 'rabbitmq:3.9-management-alpine'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ Management Plugin 포트
    deploy:
      mode: replicated
      replicas: 1
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: admin
    ports:
      - '6379:6379'
    command:
      [
        'redis-server',
        '--requirepass',
        'admin',
        '--save',
        '', # RDB 영속성 비활성화
        '--appendonly',
        'no'
      ] # AOF 영속성 비활성화
    # volumes:
    #   - ./db-data/redis:/data # Redis 데이터 저장소 마운트
