services:
  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: ./gateway-service.dockerfile
    container_name: gateway-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
    ports:
      - "2719:80"
    deploy:
      mode: replicated
      replicas: 1

  user-service:
    build:
      context: ./user-service
      dockerfile: ./user-service.dockerfile
    container_name: user-service
    restart: always
    environment:
      ONESIGNAL_APP_ID: ${ONESIGNAL_APP_ID}
      ONESIGNAL_API_KEY: ${ONESIGNAL_API_KEY}
    deploy:
      mode: replicated
      replicas: 1

  chat-service:
    build:
      context: ./chat-service
      dockerfile: ./chat-service.dockerfile
    container_name: chat-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
    deploy:
      mode: replicated
      replicas: 1

  consumer-service:
    build:
      context: ./consumer-service
      dockerfile: ./consumer-service.dockerfile
    container_name: consumer-service
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: ./auth-service.dockerfile
    container_name: auth-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
    deploy:
      mode: replicated
      replicas: 1

  match-service:
    build:
      context: ./match-service
      dockerfile: ./match-service.dockerfile
    container_name: match-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
    deploy:
      mode: replicated
      replicas: 1

  match-socket-service:
    build:
      context: ./match-socket-service
      dockerfile: ./match-socket-service.dockerfile
    container_name: match-socket-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
    deploy:
      mode: replicated
      replicas: 1

  chat-socket-service:
    build:
      context: ./chat-socket-service
      dockerfile: ./chat-socket-service.dockerfile
    container_name: chat-socket-service
    restart: always
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: admin
    deploy:
      mode: replicated
      replicas: 1

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: sample
    ports:
      - "3306:3306"
    deploy:
      mode: replicated
      replicas: 1

  mongo:
    image: "mongo:4.2.16-bionic"
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: sample

  rabbitmq:
    image: "rabbitmq:3.9-management-alpine"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ Management Plugin 포트
    deploy:
      mode: replicated
      replicas: 1
    environment:
      RABBITMQ_DEFAULT_USER: guest # 기본 사용자
      RABBITMQ_DEFAULT_PASS: guest # 기본 비밀번호
    volumes:
      - ./db-data/rabbitmq/:/var/lib/rabbitmq/

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    environment:
      REDIS_PASSWORD: admin
    ports:
      - "6379:6379"
    command: [
        "redis-server",
        "--requirepass",
        "admin",
        "--save",
        "", # RDB 영속성 비활성화
        "--appendonly",
        "no", # AOF 영속성 비활성화
      ]
    # volumes:
    #   - ./db-data/redis:/data # Redis 데이터 저장소 마운트
