apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}-auth
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-auth
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: http