apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth
  labels:
    app: {{ .Release.Name }}-auth
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-auth
  ports:
    {{- range .Values.ports }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
    {{- end }}
