global:
  imageTag: latest
  
gateway:
  enabled: true

match:
  enabled: true

game:
  enabled: true

chat:
  enabled: true

user:
  enabled: true

auth:
  enabled: true

push:
  enabled: true

infrastructure:
  enabled: true

service:
  type: ClusterIP # 서비스 타입을 NodePort로 변경
  ports:
    - name: gateway
      port: 2719
      targetPort: 80
    - name: match
      port: 2720
      targetPort: 80
    - name: game
      port: 2721
      targetPort: 80

serviceAccount:
  create: true
  name: ""
  