global:
  imageTag: latest
  
gateway:
  enabled: true

match:
  enabled: true

game:
  enabled: true

chat:
  enabled: true

user:
  enabled: true

auth:
  enabled: true

push:
  enabled: true

infrastructure:
  enabled: true

service:
  type: ClusterIP # 서비스 타입을 NodePort로 변경
  ports:
    - name: gateway
      port: 2719
      targetPort: 80
    - name: match
      port: 2720
      targetPort: 80
    - name: game
      port: 2721
      targetPort: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: api.gateway.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: gateway
          servicePort: 2719
    - host: api.match.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: match
          servicePort: 2720
    - host: api.game.com
      paths:
        - path: /
          pathType: Prefix
          serviceName: game
          servicePort: 2721
  tls:
    - hosts:
        - api.gateway.com
        - api.match.com
        - api.game.com
      secretName: tls-secret

autoscaling:
  enabled: false # autoscaling을 사용하지 않는다면 false로 설정
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
