image: baaami/doran-game
replicas: 1
service:
  type: ClusterIP
ports:
  - port: 2721
    targetPort: 80
    name: http
env:
  REDIS_HOST: doran-redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: doran-rabbitmq
  MONGO_HOST: doran-mongo
resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "400m"
    memory: "1024Mi"
autoscaling:
  enabled: true
  minReplicas: 1        # 최소 2개의 Pod 유지
  maxReplicas: 10       # 최대 10개까지 확장 가능
  targetCPUUtilizationPercentage: 70    # CPU 사용률 70% 초과시 스케일 아웃
  targetMemoryUtilizationPercentage: 80  # 메모리 사용률 80% 초과시 스케일 아웃
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60     # 스케일 업 전 대기 시간
      policies:
      - type: Pods
        value: 1                         # 한 번에 최대 2개의 Pod 추가
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300    # 스케일 다운 전 대기 시간
      policies:
      - type: Pods
        value: 1                         # 한 번에 1개의 Pod 제거
        periodSeconds: 60

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: api.solo.com
      paths:
        - path: /ws/game(/|$)(.*)
          pathType: ImplementationSpecific
          serviceName: game
          servicePort: 2721
  tls:
    - hosts:
        - api.solo.com
      secretName: tls-secret