apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: redis
        image: {{ .Values.redis.image }}
        env:
        - name: REDIS_PASSWORD
          value: {{ .Values.redis.env.REDIS_PASSWORD }}
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
      volumes:
      - name: redis-data
        hostPath:
          path: {{ .Values.redis.persistence.path }}
          type: DirectoryOrCreate