image: baaami/doran-gateway
replicas: 1
service:
  type: ClusterIP
ports:
  - port: 2719
    targetPort: 80
    name: http
env:
  REDIS_HOST: doran-redis
  REDIS_PORT: "6379"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
  hosts:
    - host: api.solo.com
      paths:
        - path: /api/v1
          pathType: Prefix
          serviceName: gateway
          servicePort: 2719
  tls:
    - hosts:
        - api.solo.com
      secretName: tls-secret