image: baaami/doran-match
replicas: 1
service:
  type: ClusterIP
ports:
  - port: 2720
    targetPort: 80
    name: http
env:
  REDIS_HOST: doran-redis
  REDIS_PORT: "6379"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: api.solo.com
      paths:
        - path: /ws/match(/|$)(.*)
          pathType: ImplementationSpecific
          serviceName: match
          servicePort: 2720
  tls:
    - hosts:
        - api.solo.com
      secretName: tls-secret