apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user
  labels:
    app: {{ .Release.Name }}-user
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-user
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-user
    spec:
      containers:
        - name: user
          image: "{{ .Values.image }}:{{ .Values.global.imageTag | default "latest" }}"
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ .targetPort }}
              name: {{ .name }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}