mysql:
  enabled: true
  image: mysql:8
  replicas: 1
  env:
    MYSQL_DATABASE: users

mongo:
  enabled: true
  image: mongo:4.2.16-bionic
  replicas: 1
  env:
    MONGO_INITDB_DATABASE: logs

rabbitmq:
  enabled: true
  image: rabbitmq:3.9-management-alpine
  replicas: 1
  env:

redis:
  enabled: true
  image: redis:alpine
  replicas: 1
  env:
