mysql:
  enabled: true
  image: mysql:8
  replicas: 1
  env:
    MYSQL_DATABASE: users
    MYSQL_ROOT_PASSWORD: sample

mongo:
  enabled: true
  image: mongo:4.2.16-bionic
  replicas: 1
  env:
    MONGO_INITDB_DATABASE: logs
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: sample

rabbitmq:
  enabled: true
  image: rabbitmq:3.9-management-alpine
  replicas: 1
  env:
    RABBITMQ_DEFAULT_USER: guest
    RABBITMQ_DEFAULT_PASS: guest

redis:
  enabled: true
  image: redis:alpine
  replicas: 1
  env:
    REDIS_PASSWORD: admin