apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.serviceName }}
  labels:
    app: {{ .Release.Name }}-{{ .Values.serviceName }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.serviceName }}
    spec:
      containers:
        - name: {{ .Values.serviceName }}
          image: "{{ .Values.image }}:{{ .Values.global.imageTag }}"
          ports:
            {{- range .Values.ports }}
            - containerPort: {{ . }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
