{{- range $name, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  labels:
    app: {{ $.Release.Name }}-{{ $name }}
spec:
  replicas: {{ $service.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: "{{ $service.image }}:{{ $.Values.global.imageTag }}"
          ports:
            {{- range $service.ports }}
            - containerPort: {{ . }}
            {{- end }}
          env:
            {{- range $key, $value := $service.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
---
{{- end }}
