{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
  labels:
    app: {{ $.Release.Name }}-{{ $name }}
spec:
  type: {{ $.Values.service.type }}
  selector:
    app: {{ $.Release.Name }}-{{ $name }}
  ports:
    {{- if $service.ports }}
    {{- range $service.ports }}
    - protocol: TCP
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
    {{- end }}
    {{- else }}
    - protocol: TCP
      port: 80
      targetPort: 80
      name: default
    {{- end }}
---
{{- end }}