{{- $name := "push" }}
{{- $service := .Values }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ $name }}
  labels:
    app: {{ .Release.Name }}-{{ $name }}
spec:
  type: {{ $service.service.type }}
  selector:
    app: {{ .Release.Name }}-{{ $name }}
  ports:
    - protocol: TCP
      port: {{ $service.service.port }}
      targetPort: {{ $service.service.port }}
      name: http