apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          env:
            {{- range $key, $value := .Values.mongo.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}