name: CI/CD Pipeline for Kubernetes

on:
  push:
    branches:
      - devel  # devel 브랜치에 푸시될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Images
        run: |
          IMAGE_TAG=${{ github.sha }}
          SERVICES=($(ls ./services))

          for SERVICE in "${SERVICES[@]}"; do
            docker build -t baaami/doran-$SERVICE:$IMAGE_TAG -t baaami/doran-$SERVICE:latest ./services/$SERVICE
            docker push baaami/doran-$SERVICE:$IMAGE_TAG
            docker push baaami/doran-$SERVICE:latest
          done

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure Kubernetes Credentials
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Deploy using Helm
        run: |
          IMAGE_TAG=${{ github.sha }}
          helm upgrade --install doran ./helm-chart -n mynamespace \
            --set global.imageTag=$IMAGE_TAG
