apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-rabbitmq
  labels:
    app: {{ .Release.Name }}-rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672
      targetPort: 5672
      protocol: TCP
      name: rabbitmq
    - port: 15672
      targetPort: 15672
      protocol: TCP
      name: management
  selector:
    app: {{ .Release.Name }}-rabbitmq
